[package]
name = "texc"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[[bin]]
name = "texc"
path = "src/texc.rs"
