#!/usr/bin/env python3

import subprocess
import time
import argparse
import re
import os.path as path

WARNING = 0
INFO    = 1
ERROR   = 2
SUCCESS = 3

color = lambda s, c: "\x1b[38;5;{}m{}\x1b[0m".format(c, s)

label_color = [
    "[ " + color("warning", 208) + " ]",
    "[ " + color("info", 39) + " ]",
    "[ " + color("error", 9) + " ]",
    "[ " + color("success", 76) + " ]",
]

label_no_color = [
    "[ warning ]",
    "[ info ]",
    "[ error ]",
    "[ success ]",
]

label = label_color

root_file = None

filepath = path.dirname(path.realpath(__file__))

def latexmk_clean():
    commands = "latexmk -c -r {}".format(
        path.join(filepath, ".latexmkrc")).split()
    subprocess.run(commands, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def latexmk_build():
    commands = "latexmk -silent -f -r {} -bibtex -pdf {}" \
        .format(path.join(filepath, ".latexmkrc"), root_file).split()
    subprocess.run(commands, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def texparse_logcheck():
    error_log = None
    error_log_path = path.abspath(re.sub("\.tex$", ".log", root_file));

    # Poll for log file until it's generated or until 'error_log_count' is
    # reached
    error_log_count = 0
    while error_log is None and error_log_count < 3:
        try:
            error_log = open(error_log_path, "r", encoding="ISO-8859-1")
            break;
        except:
            print(label[INFO] + " Waiting for the logfile...\n")
        error_log_count += 1
        time.sleep(1)
    if error_log == None:
        print(label[ERROR] + " No logfile found!\n")
        quit(1)

    line = error_log.readline()

    num_errors   = 0
    num_warnings = 0
    num_infos    = 0
    warnings     = []
    errors       = []
    infos        = []

    def consume_message(line):
        message = line.strip("\n")
        next_line = error_log.readline().rstrip("\n")
        while len(next_line) != 0:
            message += next_line
            next_line = error_log.readline().rstrip("\n")
        return message

    def index(line):
        body = consume_message(line)
        match = re.search(r"[0-9]+", body)
        if match:
            return match.group(0)
        return None

    while line:
        # Found error
        if line.find("LaTeX Error") != -1:
            line = line.strip(". \n")
            x = line.find(":")
            errors.append(label[ERROR] + " " + line[x + 2:] + "\n")
            num_errors += 1
        elif line.find("!") == 0:
            line = line.strip(". \n")
            errors.append(label[ERROR] + " " + line[2:] + "\n")
            num_errors += 1
        # Found warning
        elif line.find("LaTeX Warning") != -1:
            line = line.strip(". \n")
            x = line.find(":")
            warnings.append(label[WARNING] + " " + line[x + 2:] + "\n")
            num_warnings += 1
        # Found info
        elif line.find("Overfull") != -1:
            line = line.strip(". \n")
            infos.append(label[INFO] + " " + line + "\n")
            num_infos += 1
        line = error_log.readline()

    print()

    if num_errors == 0 and num_warnings == 0 and num_infos == 0:
        print(label[SUCCESS] + " No errors detected\n")
        return

    warnings.sort()
    errors.sort()
    infos.sort()

    for info in infos:
        print(info)
    for warning in warnings:
        print(warning)
    for error in errors:
        print(error)

def init_argparse():
    parser = argparse.ArgumentParser()

    # Clean current directory, but leave the PDF
    parser.add_argument(
        "-c",
        "--clean",
        action = "store_true",
        required = False
    )

    parser.add_argument(
        "-n",
        "--no-color",
        action = "store_true",
        required = False
    )

    # Specify root file
    parser.add_argument(
        "root_file",
        nargs = "?"
    )

    return vars(parser.parse_args())

def isset(argv, key):
    value = argv.get(key)
    return (value is not None) and (value is not False)

def argvcount(argv):
    count = 0
    for k, v in argv.items():
        count += isset(argv, k)
    return count

if __name__ == "__main__":
    argv = init_argparse()

    argc = argvcount(argv)

    if isset(argv, "no_color"):
        label = label_no_color

    if isset(argv, "clean"):
        latexmk_clean()
        quit(0)

    root_file = argv.get("root_file")
    if not path.isfile(root_file):
        print("[ERROR] Invalid root file")
        quit(1)

    time_start = time.time()
    latexmk_build()
    texparse_logcheck()
    print("Build completed in {:.1f} seconds".format(time.time() - time_start))
