#!/usr/bin/env python3

import subprocess
import os
import time
import argparse
import re

warning_label = "\x1b[38;5;208m[Warning]\x1b[0m"
info_label = "\x1b[38;5;39m[Info]\x1b[0m"
error_label = "\x1b[38;5;9m[Error]\x1b[0m"
success_label = "\x1b[38;5;76m[Success]\x1b[0m"

option_clean_current_dir = False
root_file = None
latexmkrc = os.path.join(os.path.dirname(os.path.realpath(__file__)), ".latexmkrc")

def latexmk_clean():
    commands = "latexmk -c -r {}".format(latexmkrc).split()
    latexmk_subprocess_clean = subprocess.run(
        commands, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def latexmk_simple():
    commands = "latexmk -silent -f -r {} -bibtex -pdf {}" \
        .format(latexmkrc, root_file).split()
    latexmk_subprocess_simple = subprocess.run(
        commands, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def texparse_logfile():
    error_log = None

    # Poll for 'main.log' until it's generated or until 'error_log_count' is
    # reached
    error_log_count = 0
    error_log_path = os.path.abspath("main.log")
    while error_log is None and error_log_count < 3:
        try:
            error_log = open(error_log_path, "r")
            break;
        except:
            print(info_label + " Could not find 'main.log'\n")
        error_log_count += 1
        time.sleep(1)
    if error_log == None:
        quit(1)

    line = error_log.readline()

    num_errors = 0
    num_warnings = 0
    num_infos = 0

    warnings = []
    errors = []
    infos = []

    def consume_message(line):
        message = line.strip("\n")
        next_line = error_log.readline().rstrip("\n")
        while len(next_line) != 0:
            message += next_line
            next_line = error_log.readline().rstrip("\n")
        return message

    while line:
        # Found error
        if line.find("LaTeX Error") != -1:
            line = line.strip(". \n")
            x = line.find(":")
            errors.append(error_label + " " + line[x + 2:] + "\n")
            num_errors += 1
        elif line.find("!") == 0:
            line = line.strip(". \n")
            body = consume_message(line)
            index = re.search(r"[0-9]+", body).group(0)
            errors.append(error_label + " " + line[2:] + "on line " + index + "\n")
            num_errors += 1
        # Found warning
        elif line.find("LaTeX Warning") != -1:
            line = line.strip(". \n")
            x = line.find(":")
            warnings.append(warning_label + " " + line[x + 2:] + "\n")
            num_warnings += 1
        # Found info
        elif line.find("Overfull") != -1:
            line = line.strip(". \n")
            infos.append(info_label + " " + line + "\n")
            num_infos += 1
        line = error_log.readline()

    if num_errors == 0 and num_warnings == 0 and num_infos == 0:
        print(success_label + " No errors detected\n")
        return

    warnings.sort()
    errors.sort()
    infos.sort()

    for info in infos:
        print(info)
    for warning in warnings:
        print(warning)
    for error in errors:
        print(error)

def init_argparse():
    parser = argparse.ArgumentParser()

    # Clean current directory, but leave the PDF
    parser.add_argument(
        "-c",
        action = "store_true",
        required = False
    )

    # Specify root file
    parser.add_argument(
        "root_file",
        nargs = "?"
    )

    return vars(parser.parse_args())

if __name__ == "__main__":
    argv = init_argparse()

    root_file = argv.get("root_file")
    option_clean_current_dir = argv.get("c")

    if option_clean_current_dir and root_file:
        print("[Error]  Option -c/--clean takes no arguments")
        quit(1)

    if root_file and not os.path.isfile(root_file):
        print("[Error] Invalid root file")
        quit(1)

    if option_clean_current_dir:
        latexmk_clean()
    else:
        time_start = time.time()
        latexmk_simple()
        texparse_logfile()
        print("Build-latency: {:.1f} seconds".format(time.time() - time_start))
